- deploy/openshift/test-app-template.yaml
- hack/deploy-example.sh
Considering that kiali/kiali-test-service:latest is not docker hub. 
I made some slight modification on the hack.sh script to make the images configurable on the script.
Best Regards,
> [KIALI-423] Changing Template to make images configurable

- deploy/openshift/test-app-template.yaml
Correcting the value field on the template. I committed with `default` instead of `value`.
Best Regards,
> [KIALI-423] Fixing Openshift Template

- .travis.yml
This should work, assuming DOCKER_USER and DOCKER_PASSWORD are the actual variable names that are encoded.
> will this fix the travis issue?

- test-service/deploy/ansible/README.adoc
- test-service/deploy/ansible/deploy_multiple_namespaces.yml
This playbook will allow deploying a kiali test mesh will allow a flexible mesh on flexible number of namespaces (eg: it can be 2 or 100)
Best Regards,
> [KIALI-869] Multiple Namespaces Ansible Playbook

- test-service/deploy/ansible/README.adoc
- test-service/deploy/ansible/deploy_test_multiple_namespaces_meshes.yml
@cfcosta  I forgot some minor things on the #21
> [KIALI-869] Updating the documentation and some minor things on the playbook

- Makefile
- test-service/deploy/ansible/deploy_test_multiple_namespaces_meshes.yml
Include Kiali Hourglass on Multiple Namespace
> Include Kiali test hourglass on Multiple Namespace Playbook

- ansible/README.adoc
- ansible/deploy_complex_test_mesh.yml
- Documenting components of Kiali Test Mesh.
> KIALI-1790 Document Kiali-Complex-Mesh

- traffic-generator/docker/traffic-generator.sh
Hi, 
updating Traffic Generator to produce logs on openshift logs tab.
Best Regards,
cc @jmazzitelli.
Can you update the image there?
Best Regards,
> KIALI-1857 Updating Traffic Generator

- ansible/deploy_complex_test_mesh.yml
- ansible/tasks/deploy_checker_app.yml
Hello, 
I am including the checker before traffic generator deployment on Kiali Complex Mesh. 
This will prevent failures.
Best Regards, 
> KIALI-1858 Including Checker Before Deploying Traffic Generator on Kiali Complex Mesh

- Makefile
- operator/kiali-test-mesh-operator/deploy/operator.yaml
Just moving operator to Kiali Docker hub account.
> Moving Operator to Kiali Account

- operator/kiali-test-mesh-operator/bookinfo.yml
- operator/kiali-test-mesh-operator/complex-mesh.yml
- operator/kiali-test-mesh-operator/watches.yaml
Because of https://github.com/openshift/installer/issues/1383
> Including Ansible Playbook Fallback 

- operator/kiali-test-mesh-operator/roles/bookinfo/defaults/main.yml
- Update Version of Istio 1.1.1 for Manual Injection of the sidecar
> Updating Default Version of Istio to 1.1.1

- Makefile
- operator/kiali-test-mesh-operator/build/Dockerfile
- operator/kiali-test-mesh-operator/deploy/operator.yaml
- operator/kiali-test-mesh-operator/roles/bookinfo/defaults/main.yml
- operator/kiali-test-mesh-operator/roles/bookinfo/tasks/main.yml
- operator/kiali-test-mesh-operator/roles/bookinfo/templates/bookinfo/istio/destination-rules/bookinfo-details-dr.yml
- operator/kiali-test-mesh-operator/roles/bookinfo/templates/bookinfo/istio/destination-rules/bookinfo-productpage-dr.yml
- operator/kiali-test-mesh-operator/roles/bookinfo/templates/bookinfo/istio/destination-rules/bookinfo-ratings-dr.yml
- operator/kiali-test-mesh-operator/roles/bookinfo/templates/bookinfo/istio/destination-rules/bookinfo-reviews-dr.yml
- operator/kiali-test-mesh-operator/roles/common_tasks/deploy_istio_item.yml
- operator/kiali-test-mesh-operator/roles/common_tasks/deploy_traffic_generator.yml
- operator/kiali-test-mesh-operator/roles/common_tasks/namespace.yml
- operator/kiali-test-mesh-operator/watches.yaml
- Bookinfo Details Destination Rule.
- Correctly Quoting Ansible Task
- Updating Watches
- Updating Operator Template.
- Updating names on Playbooks.
It needs #46 to be merged first
> Minor things

- operator/kiali-test-mesh-operator/roles/bookinfo/tasks/main.yml
Fixing Sidecar Injection on Traffic Generator
> KIALI-2667 Fix the Kiali Test for Sidecar

- Makefile
- operator/kiali-test-mesh-operator/build/Dockerfile
- operator/kiali-test-mesh-operator/roles/bookinfo/defaults/main.yml
Updating minor versions of Istio and Ansible Operator
> [KIALI-2707] Update Istio and Operator Version

- Makefile
- README.adoc
- operator/deploy/cr/bookinfo-cr.yaml
- operator/roles/bookinfo/defaults/main.yml
- operator/roles/bookinfo/tasks/main.yml
- operator/roles/bookinfo/templates/bookinfo-ratings-v2-mongodb.yml
- operator/roles/bookinfo/templates/bookinfo-ratings-v2-mysql.yml
- operator/roles/bookinfo/templates/mongodb/deployment.yml
- operator/roles/bookinfo/templates/mysql/deployment.yml
and minor compatibilities to run with CNI and maistra
> Adding Bookinfo Hub, Version, Bookinfo Mysql and Bookinfo MongoDB parameters

- Makefile
- operator/build/Dockerfile
- operator/roles/bookinfo/templates/bookinfo-deployment.yml
- operator/roles/bookinfo/templates/bookinfo-ratings-v2-mongodb.yml
- operator/roles/bookinfo/templates/bookinfo-ratings-v2-mysql.yml
- operator/roles/bookinfo/templates/mongodb/deployment.yml
- operator/roles/bookinfo/templates/mysql/deployment.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-daemonset.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-deployment.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-replicaset.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-statefulset.yml
- operator/roles/complex_mesh/templates/complex-mesh/workload-deployment.yml
- operator/roles/redhat_tutorial/templates/customer/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/preference/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/preference/deployment-v2.yml
- operator/roles/redhat_tutorial/templates/recommendation/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/recommendation/deployment-v2.yml
- operator/roles/scale_mesh/templates/deployment.yml
- operator/roles/traffic-generator/templates/traffic-generator.yml
- traffic-generator/openshift/traffic-generator.yaml
Removing `extensions/v1beta1` in favor of `apps/v1` for `Deployment, Replicaset, StatefulSet and DaemonSet`
> [MAISTRA-1079] Fixing Resources for OCP 4.4

- Makefile
- operator/build/Dockerfile
- operator/roles/bookinfo/templates/bookinfo-deployment.yml
- operator/roles/bookinfo/templates/bookinfo-ratings-v2-mongodb.yml
- operator/roles/bookinfo/templates/bookinfo-ratings-v2-mysql.yml
- operator/roles/bookinfo/templates/mongodb/deployment.yml
- operator/roles/bookinfo/templates/mysql/deployment.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-daemonset.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-deployment.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-replicaset.yml
- operator/roles/complex_mesh/templates/complex-mesh/app-statefulset.yml
- operator/roles/complex_mesh/templates/complex-mesh/workload-deployment.yml
- operator/roles/redhat_tutorial/templates/customer/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/preference/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/preference/deployment-v2.yml
- operator/roles/redhat_tutorial/templates/recommendation/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/recommendation/deployment-v2.yml
- operator/roles/scale_mesh/templates/deployment.yml
- operator/roles/traffic-generator/templates/traffic-generator.yml
- traffic-generator/openshift/traffic-generator.yaml
Reverts kiali/kiali-test-mesh#62
> Revert "[MAISTRA-1079] Fixing Resources for OCP 4.4"

- Makefile
- README.adoc
- operator/deploy/cr/redhat_tutorial-cr.yaml
- operator/deploy/cr/scale_mesh-cr.yaml
- operator/redhat_istio_tutorial.yml
- operator/roles/redhat_tutorial/tasks/main.yml
- operator/roles/redhat_tutorial/templates/customer/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/istio/customer-dr.yml
- operator/roles/redhat_tutorial/templates/istio/customer-gateway.yml
- operator/roles/redhat_tutorial/templates/istio/customer-route.yml
- operator/roles/redhat_tutorial/templates/istio/customer-vs.yml
- operator/roles/redhat_tutorial/templates/istio/preference-dr.yml
- operator/roles/redhat_tutorial/templates/istio/recommendation-dr.yml
- operator/roles/redhat_tutorial/templates/istio/smm.yml
- operator/roles/redhat_tutorial/templates/preference/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/preference/deployment-v2.yml
- operator/roles/redhat_tutorial/templates/recommendation/deployment-v1.yml
- operator/roles/redhat_tutorial/templates/recommendation/deployment-v2.yml
- operator/roles/redhat_tutorial/vars/main.yml
- operator/scale_mesh.yml
- operator/watches.yaml
* Including `Service Mesh Member`
* Removing redundant namespace parameter 
Image available for testing at `quay.io/kiali/kiali-test-mesh-operator:testing`
> Updating Red Hat Istio Tutorial

- operator/roles/traffic-generator/templates/traffic-generator.yml
- traffic-generator/docker/traffic-generator.sh
- traffic-generator/openshift/traffic-generator-configmap.yaml
- traffic-generator/openshift/traffic-generator.yaml
Adding silent mode for long running tests to avoid huge results.json file.
> Add silent mode

- traffic-generator/Makefile-multiarch
- traffic-generator/docker/Dockerfile-multiarch
> build arm64 and amd64 traffic gen binaries

- traffic-generator/openshift/traffic-generator.yaml
Fix for https://github.com/kiali/kiali-test-mesh/issues/77
> Fix PodSecurity violation on FIPS cluster
